### ISSUE TITLE
Problem if name, path name or other containes "," or ";"

### ISSUE THREAD

**Issue by katagen** [sigdeletras/project-reports-qgis-plugin#2]
If one of the field containes already "," or ";", the CVS file is strange, cause we have multiple rows in this case.

**Comment by sigdeletras** [comment]
Regards

I have done some tests adding for example ';' in the name of the layer and the method works correctly since in this case it encloses the text in quotes.
![image](https://user-images.githubusercontent.com/4746157/211898419-4ce897e2-4622-4c24-9b24-6a4563701742.png)

![image](https://user-images.githubusercontent.com/4746157/211898565-38723c59-fa5f-4fe5-80dc-8120eef95427.png)

In the case of the route, the same thing would happen, although it is impossible to find a route that includes a semicolon.

**Comment by katagen** [comment]
But with "," my csv has 2 columns when I open it in Excel!

**Comment by sigdeletras** [comment]
I think this question is not specifically a plugin related issue.

Try changing the import options for the Excel CSV file.

I close the topic. Thanks for the input.
